### PR TITLE
Spanish version

### PR DESCRIPTION
**Pull request by rsip22**

### CODE REVIEW

**Review by sagesharp — CHANGES_REQUESTED** [review]
¡Gracias!

The payment for Outreachy interns is less of a scholarship ("Beca") and more a fixed payment for work. Would "estipendio" be better? Another word?

**Comment by rsip22** [comment]
How about "Ayuda financiera" or "Aporte para gastos de manutención"?

**Comment by rsip22** [comment]
How about now? (Inspired by LinuxChixAr tweet)

I also updated the dates on both pt-br and es versions for this round of Outreachy.

**Comment by sagesharp** [comment]
Hi @rsip22! I'm sorry this pull request has been neglected for so long. We've actually changed the wording on the poster completely now. Would you consider retranslating this from the US letter or English A4 version?

**Pull request closed without merging**
